### ISSUE TITLE
Including basic-sequence inside another component

### ISSUE THREAD

**Issue by scottnath** [basic-web-components/basic-sequence#1]
I am trying to use basic-sequence for a list of images inside my component. When I attempt to click next/previous I get errors like this:

```
Uncaught TypeError: Cannot read property 'next' of null
```

I have no problem running this in my app outside of a component, but when I put the exact same code inside a component, it doesn't work.

Example:

```
<polymer-element name="test-basic" attributes="">
  <template>
    <style>
      :host {
        display: block;
      }
    </style>

    <button onclick="document.querySelector('#sequence').previous()">Previous</button>
    <button onclick="document.querySelector('#sequence').next()">Next</button>
    <basic-sequence id="sequence" effect="reveal" wrapAround="true">
      <img src="/bower_components/basic-sequence/images/image1.jpg">
      <img src="/bower_components/basic-sequence/images/image2.jpg">
      <img src="/bower_components/basic-sequence/images/image3.jpg">
      <img src="/bower_components/basic-sequence/images/image4.jpg">
      <img src="/bower_components/basic-sequence/images/image5.jpg">
    </basic-sequence>

  </template>
  <script>
    (function () {

      Polymer({
        // define element prototype here
      });

    })();
  </script>
</polymer-element>
```

Am I missing some setting I need to add to get this working inside of another component?

thanks,
Scott

**Comment by scottnath** [comment]
I've found a solution. The problem was that `document.querySelector('#sequence')...` wasn't being picked up by the system. I wrote this into the `<script>` area like so:

```
<link rel="import" href="../../bower_components/polymer/polymer.html">
<link rel="import" href="../../bower_components/basic-sequence/basic-sequence.html">

<polymer-element name="test-basic" attributes="">
  <template>
    <style>
      :host {
        display: block;
      }
    </style>
    <button on-click="{{ clickEventPrevious }}">Previous</button>
    <button on-click="{{ clickEventNext }}">Next</button>
    <basic-sequence id="sequence" effect="reveal" wrapAround="true">
      <img src="/bower_components/basic-sequence/images/image1.jpg">
      <img src="/bower_components/basic-sequence/images/image2.jpg">
      <img src="/bower_components/basic-sequence/images/image3.jpg">
      <img src="/bower_components/basic-sequence/images/image4.jpg">
      <img src="/bower_components/basic-sequence/images/image5.jpg">
    </basic-sequence>

  </template>
  <script>
    (function () {

      Polymer('test-basic',{
        clickEventPrevious: function() {
          this.shadowRoot.querySelector('#sequence').previous();
        },
        clickEventNext: function() {
          this.shadowRoot.querySelector('#sequence').next();
        }

      });
    })();
  </script>
</polymer-element>
```

@JanMiksovsky does this seem like the correct way to do this?

thanks,
Scott

**Comment by JanMiksovsky** [comment]
Yes, this is basically correct. You can tighten up the code using [automatic node finding](https://www.polymer-project.org/docs/polymer/polymer.html#automatic-node-finding):

```
        clickEventPrevious: function() {
          this.$.sequence.previous();
        },
        clickEventNext: function() {
          this.$.sequence.next();
        }
```

I'd been writing up a response to your question yesterday, but got sidetracked trying to come up with a way to use declarative event mapping to tighten the code even further. I was curious to see if you could write `on-click={{$.sequence.previous()}}`, and thereby avoid having to write any script at all, but Polymer's event binding syntax turns out to be more limited than that for data binding syntax. The above appears to be as concise as one can get.

As an aside, for simple cases like this element, it's not necessary to wrap the script in an anonymous function.

**Comment by scottnath** [comment]
Thanks for your help with this. I've incorporated it into a component I'm working on:

https://github.com/scottnath/polymer-picasa-album

**Comment by JanMiksovsky** [comment]
Nice!

BTW, I just wanted to make sure you were also aware of [basic-carousel](http://component.kitchen/components/basic-web-components/basic-carousel), which adds a simple pair of buttons for next/previous navigation. It also has keyboard support.

If you have any questions about that, feel free to email me at jan@component.kitchen.
